### ISSUE TITLE
Key World.Actions.GuestWarning empty in en.json

### ISSUE THREAD

**Issue by rampa3** [Neos-Metaverse/NeosLocale#242]
The key World.Actions.GuestWarning is empty in the en.json file. Is it an unused key, future use ready key, or was it just left out while writing the strings?

**Comment by Frooxius** [comment]
I've checked this, and turns out it's intentionally empty. It's for the world close dialog. If the user is host, it'll warm them that they're hosting the world, but guest doesn't have any warning at all.

I think I put it there in case we want to put text there, but it might be better to remove it and just use hardcoded empty string in the code instead of the locale key.

**Comment by rampa3** [comment]
Issue resolved.
