### ISSUE TITLE
Authors in other languages are duplicated

### ISSUE THREAD

**Issue by BlazeVR** [Neos-Metaverse/NeosLocale#382]
All languages for Neos have the same authors listed as contributors which is not the case.
This is probably triggered by the default en.json file having the authors appended accidentally each time: https://github.com/Neos-Metaverse/NeosLocale/blob/master/en.json#L3 

As an example I'm the only contributor for the Turkish language but the others are also listed:
![image](https://user-images.githubusercontent.com/65873874/115157643-a8a13400-a08a-11eb-80fd-c0b1c75551c1.png)

**Comment by Frooxius** [comment]
This is intentional, the dialog shows list of all contributors for all the loaded locale strings. If the locale has any strings that are not translated, it will fallback to the next one and pick authors from that.

**Comment by TehTurk** [comment]
Should it be like that? It seems kinda confusing visually that it's showing credit for the contributions to the language then in some part. I've always wondered myself why it was like that. I can understand the fallback, but then if your choosing a language it should show those users who contributed not the fallback language. The user choosing their language won't largely care about the fallback, but who contributed to their current language.

**Comment by 3x1t-5tyl3** [comment]
I mean german is 100% translated and it still shows backups? How does that make any sense?
![20210418222119_1](https://user-images.githubusercontent.com/61988002/115159650-87dddc00-a094-11eb-8bf7-98f412aafdfb.jpg)
I can understand the fallback to some degree but if the language is decently translated for the largest part then I doubt anyone will care for the fallback? I know I certainly wouldn't and find it actually quite confusing to see contributors on languages they don't even know. Especially for 100% translated languages such as german.

**Comment by Frooxius** [comment]
@TehTurk It definitely should be like that, because the listed people still contributed to the locale strings that the user is using and will see in the application. I'm not a fan of excluding people from being credited like that. It gets particularly notable with region languages, e.g. consider the British English one, which still uses majority of strings from English. In the future I'd like to do multiple fallbacks as well, say you know Japanese, Korean and little bit of English, it could go like ja -> ko -> en, picking up strings as available and the contributors.

@3x1t-5tyl3 Same as above, I'm not a fan of excluding people from being credited, just because their relative contribution to something is small. It's the same philosophy that's used in Creator Jam and related things - err on the safe side for crediting people. I'd rather credit than not.

For 100 % translations I can check if we can make exception and not list them, but in general if there are any partial contributions I want the credit to be there.

**Comment by TehTurk** [comment]
Hmmm okay I get why you did it like that. Thanks for the explanation Froox. I just kinda still worry about the context of the visual and how it presents to someone of the selected language background to some degree. Because while objectively yes the fallback contributes, it doesn't contribute anything new to the selected language in anyway, and by having the name it's a bit confusing and say it's contributing to the language when it isn't. It's not a super pressing issue, just something to kinda consider.

Like say 1 person does spanish, but then their name is only partially there due to how many folks have contributed to the fallback nature of things, and their efforts are minimalized to those who edited the original file.

**Comment by Frooxius** [comment]
Again, I'm not really fan of that. If someone contributed to what's being displayed, they should have a credit. Particularly when it comes to the multi-fallbacks.

I plan on expanding the credits so it's formatted a bit better (in sections by language, rather than just included in the parentheses), but I don't plan on removing the credit.

I don't understand the point with their name being only partially. It's displayed in full and at the front, along with everyone else who contributed to the displayed strings. Think about the converse scenario - someone contributes a few strings to a partial locale, let's say regional Spanish, it would exclude the people who contributed to the rest.

We can talk about restructuring of the visual so it's clearer and easier to pase, but I feel like removing people from credits shouldn't even be a debate, it's just not a thing we should be focusing on.

**Comment by TehTurk** [comment]
Ah sorry no I completely agree folks should be credited completely I didn't want to debate that It's just how its mainly presented for the most part.

Because it's like whoever did the EN locale is basically on every language as a result, which doesn't make sense to most non-en speaking users/languages communities. Or how much it's contributing to their locale too. It comes off as overcrediting then.

I understand the converse of this, it just seems like they all should start at a base line in some way, because then everything starts from the EN library no matter what. I want to credit people where they contributed, but I also want it to make sense visually to the player. 

I didn't consider we'd be able to have multi locales into regional locale within a general locale, so that makes sense in the long term of things. So hopefully it at least puts some stuff into perspective in a way.
