### ISSUE TITLE
[Discussion] German sharp s "ß" use

### ISSUE THREAD

**Issue by 3x1t-5tyl3** [Neos-Metaverse/NeosLocale#389]
Question here is if it makes sense?
In german the double s ( ß ) is used for (ss) though in austria and switzerland we don't use it and just use (ss) instead.

Given there's 2 german languages that don't use it. Does it make sense for it to exist in de-DE?
We could instead push austrian, swiss and german together into one translation and spare de-AT and de-CH

Anyone else got comments about this? Would be interesting to know.

**Comment by du27y** [comment]
The spelling reform in Germany was quite some time ago, therefore it is common to differentiate "ss" from "ß". 

I think it is important to keep the "ß" as writing words like "süß" with "ss" is literally a spelling mistake for a german

**Comment by BlazeVR** [comment]
I don't recall any usage of "ss" in popular programs I've had to set in German before, would look weird to me if I would see it though (as if the program would be a veeeeery old one). 


Since only Switzerland doesn't have it on their keyboard I would say still keep it at "ß":
> In Germany and Austria, a 'ß' key is present on computer and typewriter keyboards, normally to the right-hand end on the number row.

https://en.wikipedia.org/wiki/%C3%9F#Keyboards_and_encoding

**Comment by 3x1t-5tyl3** [comment]
Yeah I saw that yesterday aswell. We'll close this then. Thanks for the input!
